# Generated by Django 5.2 on 2025-05-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_booked_bookedevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='IS_booked',
            field=models.BooleanField(default=False),
        ),
    ]
