# Generated by Django 5.2 on 2025-05-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='IS_booked',
        ),
    ]
