# Generated by Django 4.2.11 on 2025-05-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('category', models.CharField(choices=[('social', 'Social Events (Parties, reunions, weddings)'), ('professional', 'Professional Events (Conferences, workshops)'), ('cultural', 'Cultural Events (Concerts, art exhibitions)'), ('sports', 'Sports Events (Marathons, tournaments)')], default='social', max_length=20)),
                ('Date', models.DateTimeField()),
                ('Venue', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
